### ISSUE TITLE
Additional  parameter

### ISSUE THREAD

**Issue by artyom-krot** [asmagin/Cake.Sitecore#15]
In current parameters only parameter BranchName exist. 
For example in case release/0.1 branch its value will be defined as 0.1.

Could you please add additional parameters Branch to reflect full branch name, like variable 
Compare variables Build.SourceBranchName and Build.SourceBranch in VSTS.
Link: https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts

**Comment by asmagin** [comment]
This is a specifics of VSTS. 
Why cannot you pass full Branch name?

**Comment by artyom-krot** [comment]
Current parameters file has only input parameter:
BranchName = GetParameterValue(Constants.BRANCH_NAME,                                          branchName ??                    "develop");
In case for using by VSTS it matches with vsts variable Build.SourceBranchName.
But we also have one more variable Build.SourceBranch in vsts. 
Could you please define parameter for it?
SiteCore Cake should be able to receive two values from git:
Build.SourceBranchName
Build.SourceBranch

Thats will be useful for processing in case we have folders in git for branches.
Like branchname in git release/0.1 means that we have folder release with branch 0.1 in it.

**Comment by asmagin** [comment]
Released with Nuget 1.0.1
