### ISSUE TITLE
Change function GetUnicornConfigPath

### ISSUE THREAD

**Issue by artyom-krot** [asmagin/Cake.Sitecore#20]
File parameters.cake 
I can see wrong path in the function GetUnicornConfigPath in case of Release Build configuration.
Suggested solution:
1) BuildConfiguration == "Release" instead of BuildConfiguration == "Debug"
or
2) swap paths

**Comment by asmagin** [comment]
please, provide enough details to validate issue. Description above doesn't have an overview of issue whatsoever.
