### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [asmagin/Cake.Sitecore#3]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by asmagin** [comment]
The add-in doesn't have DLL with documentation as it works similar to `Cake.Recipe`.

**Comment by asmagin** [comment]
Yaml file added, add-in published on the site.
